/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRahasiaIboyRouteImport } from './routes/panel-rahasia-iboy'
import { Route as IndexRouteImport } from './routes/index'

const PanelRahasiaIboyRoute = PanelRahasiaIboyRouteImport.update({
  id: '/panel-rahasia-iboy',
  path: '/panel-rahasia-iboy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel-rahasia-iboy': typeof PanelRahasiaIboyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel-rahasia-iboy': typeof PanelRahasiaIboyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel-rahasia-iboy': typeof PanelRahasiaIboyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/panel-rahasia-iboy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/panel-rahasia-iboy'
  id: '__root__' | '/' | '/panel-rahasia-iboy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRahasiaIboyRoute: typeof PanelRahasiaIboyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel-rahasia-iboy': {
      id: '/panel-rahasia-iboy'
      path: '/panel-rahasia-iboy'
      fullPath: '/panel-rahasia-iboy'
      preLoaderRoute: typeof PanelRahasiaIboyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRahasiaIboyRoute: PanelRahasiaIboyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
